# Fill in your AWS Access Key ID and Secret Access Key
# http://aws.amazon.com/security-credentials
development:
  access_key_id: 
  secret_access_key: 

production:
  access_key_id: 
  secret_access_key: 