test:
  name: 7seconds
  description: In 7 Seconds находит интересных людей неподалеку и соединяет вас, если симпатии взаимны. Это анонимно до тех пор, пока вы не понравитесь тому, кто вам нравится.
  host: in7secondsdev.com:3000
  fb_app_id: 
  fb_app_secret: 
  aws_access: 
  aws_secret: 
  aws_bucket: 
  fsq_key: 
  fsq_secret: 
  vk_app_id: 
  vk_web_app_id: 
  vk_secret: 
  vk_scopes: "friends,photos,status,wall,offline"
  contact_email: 
  faye_host: 

development:
  name: 7seconds Development
  description: In 7 Seconds находит интересных людей неподалеку и соединяет вас, если симпатии взаимны. Это анонимно до тех пор, пока вы не понравитесь тому, кто вам нравится.
  host: in7secondsdev.com:3000
  asset_host: in7secondsdev.com:3000
  fb_app_id: 
  fb_app_secret:
  aws_access: 
  aws_secret: 
  aws_bucket: 
  aws_path: development
  fsq_key: 
  fsq_secret: 
  vk_app_id: 
  vk_web_app_id: 
  vk_secret: 
  vk_scopes: "friends,photos,status,wall,offline,notify"
  s3_cdn: 
  contact_email: 
  ua_key: 
  ua_secret: 
  ua_master: 
  faye_host: 

production:
  name: 7seconds
  description: In 7 Seconds находит интересных людей неподалеку и соединяет вас, если симпатии взаимны. Это анонимно до тех пор, пока вы не понравитесь тому, кто вам нравится.
  host: in7seconds.com
  asset_host: in7seconds.com
  fb_app_id: 
  fb_app_secret: 
  aws_access: 
  aws_secret: 
  aws_bucket: in7seconds
  aws_path: production
  fsq_key: 
  fsq_secret: 
  vk_app_id: 
  vk_web_app_id: 
  vk_secret: 
  vk_scopes: "friends,photos,status,wall,offline,notify"
  s3_cdn: 
  contact_email: 
  ua_key: 
  ua_secret: 
  ua_master: 
  faye_host: 
