test:
  name: Ostronaut
  description: DICK
  host: in7secondsdev.com:3000
  fb_app_id: ***REMOVED***
  fb_app_secret: ***REMOVED***
  aws_access: ***REMOVED***
  aws_secret: ***REMOVED***
  aws_bucket: ***REMOVED***
  fsq_key: ***REMOVED***
  fsq_secret: ***REMOVED***
  vk_app_id: ***REMOVED***
  vk_secret: mcLC6xIOxpMApchoAg3u
  vk_scopes: "friends,photos,status,wall,offline"
  contact_email: blah@blah.com

development:
  name: 7seconds Development
  description: AWESUM
  host: in7secondsdev.com:3000
  asset_host: in7secondsdev.com:3000
  fb_app_id: 251326115000725
  fb_app_secret: 84f74e5f9546de6410610df76cc0521c
  aws_access: ***REMOVED***
  aws_secret: ***REMOVED***
  aws_bucket: ***REMOVED***
  aws_path: development
  fsq_key: ***REMOVED***
  fsq_secret: ***REMOVED***
  vk_app_id: ***REMOVED***
  vk_secret: ***REMOVED***
  vk_scopes: "friends,photos,status,wall,offline"
  s3_cdn: s3.amazonaws.com/piclar
  contact_email: blah@blah.com

production:
  name: 7seconds
  description: INSERT DESCRIPTION
  host: in7seconds.com
  asset_host: piclar.com
  fb_app_id: ***REMOVED***
  fb_app_secret: ***REMOVED***
  aws_access: ***REMOVED***
  aws_secret: ***REMOVED***
  aws_bucket: piclar
  aws_path: production
  fsq_key: ***REMOVED***
  fsq_secret: ***REMOVED***
  vk_app_id: ***REMOVED***
  vk_secret: mcLC6xIOxpMApchoAg3u
  vk_scopes: "friends,photos,status,wall,offline"
  s3_cdn: cdn.piclar.com
  contact_email: ***REMOVED***
