test:
  name: 7seconds
  description: In 7 Seconds находит тех, кому вы нравитесь неподалеку и соединяет вас если симпатия взаимна. Это анонимно до тех пор пока вы не понравитесь тому тот кто вам нравится.
  host: in7secondsdev.com:3000
  fb_app_id: 416377108420491
  fb_app_secret: d63ab873eee7b992ad53b816b848bbba
  aws_access: 0SPGHF9VGDTQXENQC282
  aws_secret: 9zscLw+Y+Mh437fHaG1h+BUCtjViDrCP8ipmJImy
  aws_bucket: ostronaut-dev
  fsq_key: 3JGS1NJOEXKRRMMRYDDGWEOOVWKHUT3MK24Y4YBTZ5BM2UZ4
  fsq_secret: HNMOAADDNV3EEX3G0XUWYS2UBWSXZCMTX0WYKS1MJXIPUNKJ
  vk_app_id: 3450705
  vk_secret: nnBnyGrt4Y8MpmiAC4DA
  vk_scopes: "friends,photos,status,wall,offline"
  contact_email: support@in7seconds.com

development:
  name: 7seconds Development
  description: In 7 Seconds находит тех, кому вы нравитесь неподалеку и соединяет вас если симпатия взаимна. Это анонимно до тех пор пока вы не понравитесь тому тот кто вам нравится.
  host: in7secondsdev.com:3000
  asset_host: in7secondsdev.com:3000
  fb_app_id: 251326115000725
  fb_app_secret: 84f74e5f9546de6410610df76cc0521c
  aws_access: 0SPGHF9VGDTQXENQC282
  aws_secret: 9zscLw+Y+Mh437fHaG1h+BUCtjViDrCP8ipmJImy
  aws_bucket: ostronaut-dev
  aws_path: development
  fsq_key: 3JGS1NJOEXKRRMMRYDDGWEOOVWKHUT3MK24Y4YBTZ5BM2UZ4
  fsq_secret: HNMOAADDNV3EEX3G0XUWYS2UBWSXZCMTX0WYKS1MJXIPUNKJ
  vk_app_id: 3429661
  vk_secret: 2TdwkRgv1T4I8fYnsa9M
  vk_scopes: "friends,photos,status,wall,offline,notify"
  s3_cdn: s3.amazonaws.com/piclar
  contact_email: support@in7seconds.com
  ua_key: t3YC1EwhSX2B-jl0XP2nvg
  ua_secret: nRah8o9GT72gsMEhth98OQ
  ua_master: swmZZidlSx2dv1RyZ1cn4w

production:
  name: 7seconds
  description: In 7 Seconds находит тех, кому вы нравитесь неподалеку и соединяет вас если симпатия взаимна. Это анонимно до тех пор пока вы не понравитесь тому тот кто вам нравится.
  host: in7seconds.com
  asset_host: piclar.com
  fb_app_id: 416377108420491
  fb_app_secret: d63ab873eee7b992ad53b816b848bbba
  aws_access: 0SPGHF9VGDTQXENQC282
  aws_secret: 9zscLw+Y+Mh437fHaG1h+BUCtjViDrCP8ipmJImy
  aws_bucket: piclar
  aws_path: production
  fsq_key: 3JGS1NJOEXKRRMMRYDDGWEOOVWKHUT3MK24Y4YBTZ5BM2UZ4
  fsq_secret: HNMOAADDNV3EEX3G0XUWYS2UBWSXZCMTX0WYKS1MJXIPUNKJ
  vk_app_id: 3450705
  vk_secret: nnBnyGrt4Y8MpmiAC4DA
  vk_scopes: "friends,photos,status,wall,offline,notify"
  s3_cdn: cdn.piclar.com
  contact_email: support@in7seconds.com
  ua_key: acjij3jDR1mkLzdEfhAfnw
  ua_secret: 6qOMa1RxQ2C9bRGsoGhFtA
  ua_master: Ld5UCuy6QTmRP873U-2LNQ