test:
  name: 7seconds
  description: In 7 Seconds находит интересных людей неподалеку и соединяет вас, если симпатии взаимны. Это анонимно до тех пор, пока вы не понравитесь тому, кто вам нравится.
  host: in7secondsdev.com:3000
  fb_app_id: 416377108420491
  fb_app_secret: d63ab873eee7b992ad53b816b848bbba
  aws_access: 0SPGHF9VGDTQXENQC282
  aws_secret: 9zscLw+Y+Mh437fHaG1h+BUCtjViDrCP8ipmJImy
  aws_bucket: ostronaut-dev
  fsq_key: 3JGS1NJOEXKRRMMRYDDGWEOOVWKHUT3MK24Y4YBTZ5BM2UZ4
  fsq_secret: HNMOAADDNV3EEX3G0XUWYS2UBWSXZCMTX0WYKS1MJXIPUNKJ
  vk_app_id: 3450705
  vk_web_app_id: 3425096
  vk_secret: nnBnyGrt4Y8MpmiAC4DA
  vk_scopes: "friends,photos,status,wall,offline"
  contact_email: support@in7seconds.com
  faye_host: http://in7secondsdev.com:9292/faye

development:
  name: 7seconds Development
  description: In 7 Seconds находит интересных людей неподалеку и соединяет вас, если симпатии взаимны. Это анонимно до тех пор, пока вы не понравитесь тому, кто вам нравится.
  host: in7secondsdev.com:3000
  asset_host: in7secondsdev.com:3000
  fb_app_id: 568003499900034
  fb_app_secret: c9bb5da44bff29b9af0aa1d232475880
  aws_access: 0SPGHF9VGDTQXENQC282
  aws_secret: 9zscLw+Y+Mh437fHaG1h+BUCtjViDrCP8ipmJImy
  aws_bucket: ostronaut-dev
  aws_path: development
  fsq_key: 3JGS1NJOEXKRRMMRYDDGWEOOVWKHUT3MK24Y4YBTZ5BM2UZ4
  fsq_secret: HNMOAADDNV3EEX3G0XUWYS2UBWSXZCMTX0WYKS1MJXIPUNKJ
  vk_app_id: 3429661
  vk_web_app_id: 3425096
  vk_secret: 2TdwkRgv1T4I8fYnsa9M
  vk_scopes: "friends,photos,status,wall,offline,notify"
  s3_cdn: cdn.in7seconds.com
  contact_email: support@in7seconds.com
  ua_key: t3YC1EwhSX2B-jl0XP2nvg
  ua_secret: nRah8o9GT72gsMEhth98OQ
  ua_master: swmZZidlSx2dv1RyZ1cn4w
  faye_host: http://in7secondsdev.com:9292/faye

production:
  name: 7seconds
  description: In 7 Seconds находит интересных людей неподалеку и соединяет вас, если симпатии взаимны. Это анонимно до тех пор, пока вы не понравитесь тому, кто вам нравится.
  host: in7seconds.com
  asset_host: in7seconds.com
  fb_app_id: 416377108420491
  fb_app_secret: d63ab873eee7b992ad53b816b848bbba
  aws_access: 0SPGHF9VGDTQXENQC282
  aws_secret: 9zscLw+Y+Mh437fHaG1h+BUCtjViDrCP8ipmJImy
  aws_bucket: in7seconds
  aws_path: production
  fsq_key: 3JGS1NJOEXKRRMMRYDDGWEOOVWKHUT3MK24Y4YBTZ5BM2UZ4
  fsq_secret: HNMOAADDNV3EEX3G0XUWYS2UBWSXZCMTX0WYKS1MJXIPUNKJ
  vk_app_id: 3450705
  vk_web_app_id: 3425096
  vk_secret: nnBnyGrt4Y8MpmiAC4DA
  vk_scopes: "friends,photos,status,wall,offline,notify"
  s3_cdn: cdn.in7seconds.com
  contact_email: support@in7seconds.com
  ua_key: acjij3jDR1mkLzdEfhAfnw
  ua_secret: 6qOMa1RxQ2C9bRGsoGhFtA
  ua_master: Ld5UCuy6QTmRP873U-2LNQ
  faye_host: http://in7seconds.com:9292/faye
