default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: in7seconds_development
  pool: 25
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: in7seconds_development

test:
  <<: *default
  database: in7seconds_test

production:
  <<: *default
  database: in7seconds_production
  username: master
  password: stanf0rd
  host: linksie.cvlxmdsey5id.eu-west-1.rds.amazonaws.com
